platform :ios, '5.0'

PODSPEC = 'https://raw.github.com/steakknife/' +
            'REActivityViewController/master/' +
            'REActivityViewController.podspec'

%w|Facebook Twitter VK Tumblr Message Mail Safari Chrome Pocket Instapaper| +
%w|Readability Diigo Kippt SaveToCameraRoll Maps Print Copy|.map { |activity|
  pod "REActivityViewController/Activity/#{activity}", :podspec => PODSPEC
}

# or all activities
#pod 'REActivityViewController/Activity', :podspec => PODSPEC

# all localizations
pod 'REActivityViewController/Localization', :podspec => PODSPEC

# or everything
#pod 'REActivityViewController', :podspec => PODSPEC
