// REConfig.h

#ifdef COCOAPODS

// enabled what's configured
#include "../Pods-environment.h"

#else // enable everything
// prevent reinclusion
#define COCOAPODS

#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Mail
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Print
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Copy
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Maps
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_SaveToCameraRoll
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Facebook
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Twitter
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Message
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Safari
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Chrome
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Tumblr
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_VK
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Instapaper
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Pocket
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Readability
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Diigo
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_Kippt
#define COCOAPODS_POD_AVAILABLE_REActivityViewController_Activity_SinaWeibo

#endif
